# Generated by Django 5.0.1 on 2026-01-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='admin_review_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='installation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='charger_installation_type',
            field=models.CharField(blank=True, choices=[('wall-mounted', 'Wall Mounted'), ('pedestal', 'Pedestal'), ('floor-mounted', 'Floor Mounted')], max_length=20),
        ),
        migrations.AddField(
            model_name='installation',
            name='charger_manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='installation',
            name='charger_model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='installation',
            name='charger_power_output',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='installation',
            name='customer_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='installation',
            name='customer_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='installation',
            name='customer_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='installation',
            name='customer_street',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='installation',
            name='documentation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='installation',
            name='installation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='installation',
            name='notes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='installation',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='installation',
            name='property_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='installation',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='scheduling_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='installation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='survey_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='installer',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='installer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='installer',
            name='compliance_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='installer',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('certificate', 'Certificate'), ('invoice', 'Invoice'), ('document', 'Document'), ('survey', 'Survey'), ('completion', 'Completion'), ('other', 'Other')], default='photo', max_length=20),
        ),
        migrations.AlterField(
            model_name='installation',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='status',
            field=models.CharField(choices=[('pending_assignment', 'Pending Assignment'), ('pending_acceptance', 'Pending Acceptance'), ('declined', 'Declined'), ('rejected_by_installer', 'Rejected by Installer'), ('accepted', 'Accepted'), ('survey_in_progress', 'Survey In Progress'), ('pending_customer_approval', 'Pending Customer Approval'), ('approved_for_installation', 'Approved for Installation'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('testing', 'Testing'), ('completed', 'Completed'), ('under_admin_review', 'Under Admin Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('on_hold', 'On Hold'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('cancelled', 'Cancelled')], default='pending_assignment', max_length=30),
        ),
    ]
